"""
generate_gh_pages_simulation.py
---------------------------------
Prepares the `public/` directory for deployment by copying the EXACT HTML files 
(`conflicts_tree.html` and `isolated_prs.html`) generated by running main.py / dashboard.py,
attaching the Maintainer Snapshot Notice, and creating `public/index.html`.
"""

import os
import re
import shutil

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
PUBLIC_DIR = os.path.join(ROOT_DIR, "public")

os.makedirs(PUBLIC_DIR, exist_ok=True)

SNAPSHOT_BANNER = """
    <div style="background:linear-gradient(90deg, #1e40af 0%, #3b82f6 100%);color:#ffffff;padding:12px 20px;border-radius:10px;font-size:14px;font-weight:600;display:flex;align-items:center;gap:12px;margin-bottom:24px;box-shadow:0 4px 12px rgba(30,64,175,0.25)">
        <span style="font-size:20px;background:rgba(255,255,255,0.2);padding:6px;border-radius:50%;display:inline-flex;align-items:center;justify-content:center">&#128247;</span>
        <div>
            <span style="text-transform:uppercase;letter-spacing:0.6px;background:#ffffff;color:#1e40af;padding:3px 10px;border-radius:6px;font-size:11px;font-weight:800;margin-right:8px;display:inline-block">Maintainer Snapshot</span>
            <span style="font-weight:700;text-decoration:underline;text-underline-offset:3px">This is a snapshot taken at that time.</span> Captured by maintainer for audience analysis &amp; interactive simulation.
        </div>
    </div>
"""

def add_banner_to_html(content):
    if "This is a snapshot taken at that time" not in content:
        match = re.search(r"<body\b[^>]*>", content, re.IGNORECASE)
        if not match:
            raise ValueError("No opening <body> tag found in HTML content")
        return content[:match.end()] + f"\n{SNAPSHOT_BANNER}" + content[match.end():]
    return content

def prepare_deployment():
    # 1. Read exact root conflicts_tree.html
    conflicts_path = os.path.join(ROOT_DIR, "conflicts_tree.html")
    if not os.path.exists(conflicts_path):
        raise FileNotFoundError(f"Required HTML report not found: {conflicts_path}")
    with open(conflicts_path, "r", encoding="utf-8") as f:
        conflicts_content = f.read()
    conflicts_content = add_banner_to_html(conflicts_content)

    # 2. Read exact root isolated_prs.html
    isolated_path = os.path.join(ROOT_DIR, "isolated_prs.html")
    if not os.path.exists(isolated_path):
        raise FileNotFoundError(f"Required HTML report not found: {isolated_path}")
    with open(isolated_path, "r", encoding="utf-8") as f:
        isolated_content = f.read()
    isolated_content = add_banner_to_html(isolated_content)

    # 3. Create index.html simulation hub
    index_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Pull Request Simulation Dashboard — MiniChain</title>
<style>
  *{{box-sizing:border-box;margin:0;padding:0}}
  body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f3f4f6;color:#111;padding:24px;max-width:1200px;margin:0 auto}}
  h1{{font-size:24px;font-weight:800;margin-bottom:6px}}
  .sub{{font-size:14px;color:#6b7280;margin-bottom:24px}}
  .nav-bar{{display:flex;gap:12px;margin-bottom:24px}}
  .nav-link{{padding:10px 18px;background:#fff;border:1px solid #e5e7eb;border-radius:8px;color:#1d4ed8;font-weight:700;text-decoration:none;box-shadow:0 1px 3px rgba(0,0,0,0.05)}}
  .nav-link:hover{{background:#eff6ff}}
  .grid{{display:grid;grid-template-columns:1fr 1fr;gap:20px}}
  .card{{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:24px;box-shadow:0 2px 8px rgba(0,0,0,0.05);display:flex;flex-direction:column;justify-content:space-between}}
  .card h2{{font-size:18px;margin-bottom:10px;color:#111827}}
  .card p{{font-size:13px;color:#4b5563;line-height:1.6;margin-bottom:20px}}
  .btn{{display:inline-block;padding:10px 16px;background:#1d4ed8;color:#fff;font-weight:700;text-decoration:none;border-radius:6px;text-align:center}}
</style>
</head>
<body>

{SNAPSHOT_BANNER}

<h1>Pull Request Simulation Dashboard</h1>
<p class="sub">StabilityNexus/MiniChain &middot; Maintainer Interactive Simulation</p>

<div class="nav-bar">
  <a class="nav-link" href="conflicts_tree.html">⚡ PR Idea Conflicts View</a>
  <a class="nav-link" href="isolated_prs.html">✅ Isolated PRs View</a>
</div>

<div class="grid">
  <div class="card">
    <div>
      <span style="background:#fef2f2;color:#dc2626;padding:4px 8px;border-radius:4px;font-size:11px;font-weight:700;text-transform:uppercase;display:inline-block;margin-bottom:8px">Idea Conflicts</span>
      <h2>PR Idea Conflicts Tree</h2>
      <p>Interactive decision tree and head-to-head comparison for PRs solving identical problems.</p>
    </div>
    <a class="btn" href="conflicts_tree.html">Open Conflicts Simulation &rarr;</a>
  </div>

  <div class="card">
    <div>
      <span style="background:#f0fdf4;color:#166534;padding:4px 8px;border-radius:4px;font-size:11px;font-weight:700;text-transform:uppercase;display:inline-block;margin-bottom:8px">Isolated PRs</span>
      <h2>Isolated Pull Requests</h2>
      <p>Analysis of PRs solving standalone, non-overlapping problems with CodeRabbit review walkthroughs and risk assessments.</p>
    </div>
    <a class="btn" style="background:#059669" href="isolated_prs.html">Open Isolated PRs Simulation &rarr;</a>
  </div>
</div>

</body>
</html>"""

    # Write exact files to public/
    with open(os.path.join(PUBLIC_DIR, "conflicts_tree.html"), "w", encoding="utf-8") as f:
        f.write(conflicts_content)
    with open(os.path.join(PUBLIC_DIR, "conflicts.html"), "w", encoding="utf-8") as f:
        f.write(conflicts_content)
    with open(os.path.join(PUBLIC_DIR, "isolated_prs.html"), "w", encoding="utf-8") as f:
        f.write(isolated_content)
    with open(os.path.join(PUBLIC_DIR, "isolated.html"), "w", encoding="utf-8") as f:
        f.write(isolated_content)
    with open(os.path.join(PUBLIC_DIR, "index.html"), "w", encoding="utf-8") as f:
        f.write(index_content)

    # Clean up redundant docs/ folder if present
    docs_dir = os.path.join(ROOT_DIR, "docs")
    if os.path.exists(docs_dir):
        shutil.rmtree(docs_dir)

    print("Successfully prepared public/ as the sole deployment folder and removed redundant docs/ directory.")

if __name__ == "__main__":
    prepare_deployment()
